<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 2018/5/6
 * Time: 下午1:08
 */

namespace App\Src\From\User;


use App\Src\From\Form;

class LoginFrom extends Form
{
    public function rules()
    {
        // TODO: Implement rules() method.
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function validation()
    {
        // TODO: Implement validation() method.
    }
}