<?php

namespace App\Console\Commands\WebSocket;

use App\Console\WebSocket;
use Illuminate\Support\Facades\Redis;
use swoole_websocket_frame;
use swoole_websocket_server;
use swoole_process;

class Server extends WebSocket
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'web:socket:server';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param swoole_websocket_server $server
     */
    protected function ready(swoole_websocket_server $server)
    {
        // 后台消息传递
        $process = new swoole_process(function ($process) use ($server) {
            while (true) {
                if($data = Redis::brpop('xxxxxx',3)){
                    foreach ($server->connections as $fd){
                        $server->push($fd,$data[1]);
                    }
                }
            }
        });
        $server->addProcess($process);
        parent::ready($server); // TODO: Change the autogenerated stub
    }


    /**
     * @return mixed|void
     */
    public function onConstruct()
    {
        // TODO: Implement onConstruct() method.
    }

    /**
     * @param swoole_websocket_server $server
     * @param swoole_websocket_frame $frame
     */
    public function message(swoole_websocket_server $server, swoole_websocket_frame $frame)
    {
        // TODO: Implement message() method.
    }

    /**
     * @param swoole_websocket_server $server
     * @param $request
     */
    public function connect(swoole_websocket_server $server, $request)
    {
        // TODO: Implement connect() method.
    }

    /**
     * @param $ser
     * @param $fd
     * @return mixed|void
     */
    public function close($ser, $fd)
    {
        // TODO: Implement close() method.
    }

}
